### PR TITLE
refactor: use num_enum to clean up the System type

### PR DESCRIPTION
**Pull request by Pr0methean**

### CODE REVIEW

**Comment by Pr0methean** [comment]
@cosmicexplorer Please upload your GPG key CE8D0DA71DEFC1DF to your GitHub account so your signature can be verified.

**Comment by cosmicexplorer** [comment]
@Pr0methean that was an old key which I have since rotated. I have been recreating signed commits in replies to the PRs you have created here--will that be ok?

**Comment by cosmicexplorer** [comment]
@Pr0methean thanks so much for creating this PR! I have rebased and fixed merged conflicts at https://github.com/zip-rs/zip2/compare/master...cosmicexplorer:zip:oldpr395?expand=1 or https://github.com/zip-rs/zip2/commit/3cfbdfca83cc3a3ca32845460b6f224c6ce272e2.

**Comment by Pr0methean** [comment]
Replaced by #77.

**Pull request closed without merging**
