### PR TITLE
feat: Add support for extended timestamps

### PR DESCRIPTION
**Pull request by Pr0methean**
This replaces https://github.com/zip-rs/zip-old/pull/437.

### CODE REVIEW

**Comment by Pr0methean** [comment]
@janstarke Please sign your commits.

**Comment by janstarke** [comment]
> @janstarke Please sign your commits.

I do not have write access to this repo. I signed the commits in the original forked repo, but I assume this is not what you was asking for.

**Comment by Pr0methean** [comment]
That is indeed what I need. Your last few commits at https://github.com/zip-rs/zip-old/compare/master...janstarke:zip-old:master still aren't showing up as Verified. Try squashing them into one and force-pushing.

**Comment by janstarke** [comment]
That's what I did, but it seems that the new commits don't show up in [oldpr437](https://github.com/zip-rs/zip2/tree/oldpr437) :cry: I don't know what happens with a PR when someone does a force-push. Do you know how I can fix it?

**Comment by Pr0methean** [comment]
Replaced by #82.

**Pull request closed without merging**
