### PR TITLE
Remove `num_enum`

### PR DESCRIPTION
**Pull request by Jake-Shadle**
Someone posted a PR to update zip to 1.0 and my CI caught that there were duplicate versions of toml being used due to num_enum. This crate is using the dependency for a single enum with 3 variants, which IMO doesn't really warrant and entire proc macro that also pulls in a toml parser.

### CODE REVIEW

**Comment by Pr0methean** [comment]
@Jake-Shadle Could you please sign your commit with a GPG key, or remake this PR in the web editor? We need commits to be Verified.

**Comment by Jake-Shadle** [comment]
Done.

**Comment by Pr0methean** [comment]
Thanks! It may take a day or two for this to be merged, because a fuzz test has a pre-existing intermittent failure that started yesterday.

**Review by cosmicexplorer — APPROVED** [review]
@Jake-Shadle thanks so much for jumping in and fixing this! I totally agree with this change.

**Pull request merged**
