### PR TITLE
perf: use indexmap in read::zip_archive::Shared instead of a separate vec and hashmap

### PR DESCRIPTION
**Pull request by Pr0methean**
This replaces https://github.com/zip-rs/zip-old/pull/396.

### CODE REVIEW

**Comment by Pr0methean** [comment]
@cosmicexplorer Please sign your commits.

**Comment by cosmicexplorer** [comment]
@Pr0methean thank you so much for creating this PR! I have rebased and fixed merge conflicts for this PR: see https://github.com/zip-rs/zip2/compare/master...cosmicexplorer:zip:oldpr396?expand=1 or https://github.com/zip-rs/zip2/commit/44c607fa4fa5d8c6a3979e29d6b2daa28d17a706. Thanks!

**Comment by cosmicexplorer** [comment]
Created #74 instead with updated commits!

**Comment by Pr0methean** [comment]
Replaced by #74

**Pull request closed without merging**
