### PR TITLE
fix: Forcibly disable encryption when adding symlinks

### PR DESCRIPTION
**Pull request by kyrias**

### CODE REVIEW

**Comment by Pr0methean** [comment]
Didn't https://github.com/zip-rs/zip2/commit/6d7c7fa57aeeeed71ca4ea54acb65266d6a28c9a fix this?

**Comment by kyrias** [comment]
How would it have?

**Comment by Pr0methean** [comment]
By ensuring that the AES extra-data field still gets added, even if we were in `writing-raw` mode when we wrote the symlink's header and target path.

**Comment by kyrias** [comment]
Right, so it would maybe make it *work* right now, but it seems rather weird to even try to encrypt them at all since they're not regular files.  I guess I could check how other implementations handle it, but I would expect them to be left unencrypted.

**Comment by Pr0methean** [comment]
I'd think it should be possible to encrypt a symlink's target -- after all, the ZIP format does have a variant that encrypts *all* metadata including the central directory and the local file headers, and it's a limitation of this crate that we can't currently read or write a file with metadata encryption. Symlink targets are an exception to that limitation because they happen to be represented the same way as a file's contents.

**Comment by kyrias** [comment]
Fair enough, though the AES encryption standard is a WinZip extension so PKWARE's intentions aren't really relevant here.  But then WinZip doesn't support symlinks anyway, so I doubt they'd care much either way.  Anyway, it seems to be interoperable with at least 7zip's implementation, so seems good.

**Pull request closed without merging**
