### PR TITLE
doc(examples): Use clap to parse args and add compression method argument in write_dir example

### PR DESCRIPTION
**Pull request by Pr0methean**
This replaces https://github.com/zip-rs/zip-old/pull/426.

### CODE REVIEW

**Comment by allilo1** [comment]
@Pr0methean can you clarify how to sign the commits? I haven't done this before but I see this page https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification. 

Does clap need to be frozen since it's declared in `dev-dependencies`?

**Comment by Pr0methean** [comment]
Yes; even dev-dependencies need to be available for tests (including doctests and examples) at MSRV.

To sign your commits, follow these guides:
1. https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key
2. https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account
3. https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key
4. https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by allilo1** [comment]
@Pr0methean I will pin clap to https://crates.io/crates/clap/4.4.18
I generated the key so my new commit should be signed, is there a recommended way to sign the old commits?

**Comment by Pr0methean** [comment]
The simplest way is probably to squash all your commits into one and open a new PR.

**Comment by allilo1** [comment]
Thanks, here's the new PR: [zip-rs#452](https://github.com/zip-rs/zip-old/pull/452)

**Comment by Pr0methean** [comment]
Moved back to this repo as #96.

**Pull request closed without merging**
