### PR TITLE
perf: Faster cde rejection (prerequires #87)

### PR DESCRIPTION
**Pull request by Pr0methean**
This replaces #47.

### CODE REVIEW

**Comment by Pr0methean** [comment]
This cannot be merged until #87 is merged, because I rewrote it to anticipate the replacement of the `byteorder` crate with `LittleEndianReadExt` and `LittleEndianWriteExt`. (If I hadn't done so, this PR would block #87 from merging.)

**Comment by Pr0methean** [comment]
Rebased this PR because https://github.com/zip-rs/zip2/actions/runs/8945282269/job/24574475474?pr=85 wasn't going to finish before it timed out.

**Comment by Pr0methean** [comment]
Closing because this causes a severe performance regression in fuzz_read.

**Comment by caldwell** [comment]
Sorry I lost track of this, the pr moved several times. It's a _significant_ improvement over the original code (in the 400x faster range)… Why didn't this get merged? Is there something I can do to help?

**Comment by Pr0methean** [comment]
Try redeveloping and retesting it against the current mainline.

**Comment by Pr0methean** [comment]
@caldwell I believe #93 renders this PR obsolete. If not, could you please open a new PR?

**Pull request closed without merging**
