### PR TITLE
fix: do not panic in Drop when stream is in an error state

### PR DESCRIPTION
**Pull request by Pr0methean**
This replaces https://github.com/zip-rs/zip-old/pull/433.

### CODE REVIEW

**Comment by Pr0methean** [comment]
@wolfv Please sign your commits.

**Comment by wolfv** [comment]
How do I do that? :) 

Thanks for taking over, by the way.

**Comment by Pr0methean** [comment]
NB: Enabling signatures in Git isn't retroactive, so you may need to rebase and squash the PR as well.

**Comment by Pr0methean** [comment]
This is no longer needed, since I rewrote Drop to fix the LZMA memory leak. We now just make a best effort to empty the stream into sink() with io::copy.

**Comment by wolfv** [comment]
Awesome!

**Pull request closed without merging**
