### PR TITLE
perf:  Faster cde rejection

### PR DESCRIPTION
**Pull request by Pr0methean**
This replaces https://github.com/zip-rs/zip-old/pull/412.

### CODE REVIEW

**Comment by Pr0methean** [comment]
@caldwell Please sign your commits.

**Comment by caldwell** [comment]
I updated [my branch](https://github.com/caldwell/zip-rs/tree/faster-cde-rejection) and github is now [marking them as verified](https://github.com/caldwell/zip-rs/commits/faster-cde-rejection/).
Unfortunately it looks like that didn't propagate here because this pr got recreated on a different repo. Would you like me to resubmit a new pr or do you want to just fetch the amended commits yourself?

**Comment by Pr0methean** [comment]
Could you please open a new one? Squashing it into one commit will probably fix the signature verification.

**Comment by Pr0methean** [comment]
Replaced by #85.

**Pull request closed without merging**
