### PR TITLE
zip64: fix zip64 extended information issue

### PR DESCRIPTION
**Pull request by onlyxuyang**
Fix zip64 extended information issue to fix zip file incorrect if size larger than 4GB.

According zip format 4.5.3:
> The order of the fields in the zip64 extended 
      information record is fixed, but the fields MUST
      only appear if the corresponding Local or Central
      directory record field is set to 0xFFFF or 0xFFFFFFFF.

### CODE REVIEW

**Comment by ChieloNewctle** [comment]
This PR fixes #192 tested with [the code snippets in #192](https://github.com/zip-rs/zip2/issues/192#issuecomment-2167112917).

**Comment by wolfv** [comment]
This does indeed fix an issue we have seen in rattler-build. Would be great if this can get merged and released. Let me know if there is any way we can help!

**Review by Pr0methean — APPROVED** [review]

**Comment by onlyxuyang** [comment]
CI failed in aes_crypto case, need more investigate.

**Comment by onlyxuyang** [comment]
sorry, pull request status is not well, close this pull request and key a new PR.

**Comment by onlyxuyang** [comment]
new PR created https://github.com/zip-rs/zip2/pull/265 fix issue in crypto case.

**Pull request closed without merging**
